# @package _global_
lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 25 #reduce LR after 25 epochs
    gamma: 0.3 #reduce LR by 70% at step_size
  interval: epoch
